//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codity.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codity.Services.Resources.NotificationTranslations", typeof(NotificationTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Hello, {0}!&lt;/strong&gt;
        ///&lt;p&gt;Your password has been changed.&lt;/p&gt;
        ///&lt;p&gt;If it wasn&apos;t You click the link below to reset Your password.&lt;/p&gt;
        ///&lt;a href=&quot;{1}&quot; target=&quot;_blank&quot;&gt;Reset Password!&lt;/a&gt;.
        /// </summary>
        internal static string ChangePasswordEmail {
            get {
                return ResourceManager.GetString("ChangePasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change.
        /// </summary>
        internal static string ChangePasswordEmailTitle {
            get {
                return ResourceManager.GetString("ChangePasswordEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Hello, {0}!&lt;/strong&gt;
        ///&lt;p&gt;We need to verify Your email address. Click the link below to confirm.&lt;/p&gt;
        ///&lt;a href=&quot;{1}&quot; target=&quot;_blank&quot;&gt;Confirm Email!&lt;/a&gt;.
        /// </summary>
        internal static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Your Email.
        /// </summary>
        internal static string ConfirmEmailTitle {
            get {
                return ResourceManager.GetString("ConfirmEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Hello, {0}!&lt;/strong&gt;
        ///&lt;p&gt;To reset Your password click the link below.&lt;/p&gt;
        ///&lt;a href=&quot;{1}&quot; target=&quot;_blank&quot;&gt;Reset Password!&lt;/a&gt;.
        /// </summary>
        internal static string ForgetPasswordEmail {
            get {
                return ResourceManager.GetString("ForgetPasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ForgetPasswordEmailTitle {
            get {
                return ResourceManager.GetString("ForgetPasswordEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        internal static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} replied on {1} user Post..
        /// </summary>
        internal static string NewComment {
            get {
                return ResourceManager.GetString("NewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} followed {1}..
        /// </summary>
        internal static string NewFollower {
            get {
                return ResourceManager.GetString("NewFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} liked {1} user Post..
        /// </summary>
        internal static string NewLike {
            get {
                return ResourceManager.GetString("NewLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} shared new Post..
        /// </summary>
        internal static string NewPost {
            get {
                return ResourceManager.GetString("NewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman.
        /// </summary>
        internal static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} replied on Your Post..
        /// </summary>
        internal static string YoursNewComment {
            get {
                return ResourceManager.GetString("YoursNewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} followed You..
        /// </summary>
        internal static string YoursNewFollower {
            get {
                return ResourceManager.GetString("YoursNewFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} liked Your Post..
        /// </summary>
        internal static string YoursNewLike {
            get {
                return ResourceManager.GetString("YoursNewLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} users liked Your Post..
        /// </summary>
        internal static string YoursNewLikes {
            get {
                return ResourceManager.GetString("YoursNewLikes", resourceCulture);
            }
        }
    }
}
